import umami from "../assets/png/umami.png";
import silentPool from "../assets/png/silent-pool.png";
import stockholm from "../assets/png/stockholm.png";
import mrGaston from "../assets/png/mr-gaston.png";

export const ProductData = [
  {
    productImage: umami,
    id: 1,
    brandName: "Umami",
    price: 30,
    typeOfDrink: "Gin",
  },
  {
    productImage: silentPool,
    id: 2,
    brandName: "Silent Pool",
    price: 31,
    typeOfDrink: "Gin",
  },
  {
    productImage: stockholm,
    id: 3,
    brandName: "Stockholms",
    price: 31,
    typeOfDrink: "Gin",
  },
  {
    productImage: mrGaston,
    id: 4,
    brandName: "Mr Gaston",
    price: 33,
    typeOfDrink: "Brandy",
  },
  {
    productImage: umami,
    id: 5,
    brandName: "Umami",
    price: 30,
    typeOfDrink: "Gin",
  },
  {
    productImage: silentPool,
    id: 6,
    brandName: "Silent Pool",
    price: 31,
    typeOfDrink: "Gin",
  },
  {
    productImage: stockholm,
    id: 7,
    brandName: "Stockholms",
    price: 31,
    typeOfDrink: "Gin",
  },
  {
    productImage: mrGaston,
    id: 8,
    brandName: "Mr Gaston",
    price: 33,
    typeOfDrink: "Brandy",
  },
  {
    productImage: umami,
    id: 9,
    brandName: "Umami",
    price: 30,
    typeOfDrink: "Gin",
  },
  {
    productImage: silentPool,
    id: 10,
    brandName: "Silent Pool",
    price: 31,
    typeOfDrink: "Gin",
  },
  {
    productImage: stockholm,
    id: 11,
    brandName: "Stockholms",
    price: 31,
    typeOfDrink: "Gin",
  },
  {
    productImage: mrGaston,
    id: 12,
    brandName: "Mr Gaston",
    price: 33,
    typeOfDrink: "Brandy",
  },
  {
    productImage: umami,
    id: 13,
    brandName: "Umami",
    price: 30,
    typeOfDrink: "Gin",
  },
  {
    productImage: silentPool,
    id: 14,
    brandName: "Silent Pool",
    price: 31,
    typeOfDrink: "Gin",
  },
  {
    productImage: stockholm,
    id: 15,
    brandName: "Stockholms",
    price: 31,
    typeOfDrink: "Gin",
  },
  {
    productImage: mrGaston,
    id: 16,
    brandName: "Mr Gaston",
    price: 33,
    typeOfDrink: "Brandy",
  },
  {
    productImage: umami,
    id: 17,
    brandName: "Umami",
    price: 30,
    typeOfDrink: "Gin",
  },
  {
    productImage: silentPool,
    id: 18,
    brandName: "Silent Pool",
    price: 31,
    typeOfDrink: "Gin",
  },
  {
    productImage: stockholm,
    id: 19,
    brandName: "Stockholms",
    price: 31,
    typeOfDrink: "Gin",
  },
  {
    productImage: mrGaston,
    id: 20,
    brandName: "Mr Gaston",
    price: 33,
    typeOfDrink: "Brandy",
  },
];
